//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mk_management.common {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BDD_RESX {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BDD_RESX() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mk_management.common.BDD_RESX", typeof(BDD_RESX).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `aaa_base` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`UsuarioCreo` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`FechaCreo` DATETIME NULL DEFAULT NULL,
        ///	`FechaElimino` DATETIME NULL DEFAULT NULL,
        ///	`UsuarioElimino` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_c [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string aaa_base {
            get {
                return ResourceManager.GetString("aaa_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `app_setting` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`UsuarioCreo` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Config` LONGTEXT NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`FechaCreo` DATETIME NULL DEFAULT NULL,
        ///	`FechaElimino` DATETIME NULL DEFAULT NULL,
        ///	`Us [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string app_setting {
            get {
                return ResourceManager.GetString("app_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPLACE INTO `app_setting` (`Id`, `AppId`, `AppVersion`, `PcHost`, `UsuarioCreo`, `Config`, `FechaCreo`, `FechaElimino`, `UsuarioElimino`, `Activo`, `Token`) VALUES
        ///	(&apos;20200213_014602_0646&apos;, &apos;@AppId&apos;, &apos;@AppVersion&apos;, &apos;@PcHost&apos;, &apos;@Usuario&apos;, &apos;YyjCwTtC3mwLZEVTqUXw9szr1dIyla5HicCPAo08c3wzZKXAYwfYaW1cbfugH5xyS+Zcs3EVfBVH5Qdi2j984XllV2y5uZdLGVQ2VT5/eLHfwY0UdQ3+pUty3ys4CqBuTM0G6eJxfXtp1s54h1FvI6kZ761v9df8gf64Ryd1/fnjAFH0wVANbgKdY3xEwkkjeaaEWv9SjBhOa1rvXRMeIvyPrQIIfS3uljSiAP212Wb1I1CRZc6Kfq0QmzGjK8+aKVZD/bUZEuUm/8g2 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string app_setting_data {
            get {
                return ResourceManager.GetString("app_setting_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `bitacora_sistema` (
        ///	`Id` INT(11) NOT NULL AUTO_INCREMENT,
        ///	`Titulo` VARCHAR(300) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Observacion` TEXT NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`EsError` BIT(1) NULL DEFAULT NULL,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`UsuarioCreo` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_genera [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string bitacora_sistema {
            get {
                return ResourceManager.GetString("bitacora_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE DATABASE IF NOT EXISTS `@bdd`;
        ///USE `@bdd`;.
        /// </summary>
        internal static string crear_bdd {
            get {
                return ResourceManager.GetString("crear_bdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `formatos_rpt` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Nombre` VARCHAR(200) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Codigo` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Formato` LONGBLOB NULL DEFAULT NULL,
        ///	`Impresora` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string formatos_rpt {
            get {
                return ResourceManager.GetString("formatos_rpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `perfil_hotspot` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`IdServer` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Descripcion` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Kb_Descarga` INT(11) NULL DEFAULT NULL,
        ///	`Kb_Subida` INT(11) NULL DEFAULT NULL,
        ///	`Minutos` INT(11) NULL DEFAULT NULL,
        ///	`HP_Id` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string perfil_hotspot {
            get {
                return ResourceManager.GetString("perfil_hotspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `perfil_sistema` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Nombre` VARCHAR(100) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`FormulariosAcceso` LONGTEXT NOT NULL COLLATE &apos;utf8mb4_bin&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`UsuarioCreo` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`FechaCreo` DATETIME NULL DE [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string perfil_sistema {
            get {
                return ResourceManager.GetString("perfil_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO `perfil_sistema` (`Id`, `Nombre`, `FormulariosAcceso`, `AppId`, `AppVersion`, `PcHost`, `UsuarioCreo`, `FechaCreo`, `FechaElimino`, `UsuarioElimino`, `Token`, `Activo`) VALUES (&apos;20190624_232737_0698&apos;, &apos;Admin&apos;, &apos;[\r\n  {\r\n    &quot;Seleccionar&quot;: true,\r\n    &quot;Grupo&quot;: false,\r\n    &quot;Formulario&quot;: &quot;aceAppSetting&quot;,\r\n    &quot;Descripcion&quot;: &quot;   Conexión base de datos&quot;\r\n  },\r\n  {\r\n    &quot;Seleccionar&quot;: true,\r\n    &quot;Grupo&quot;: false,\r\n    &quot;Formulario&quot;: &quot;aceDispositivos&quot;,\r\n    &quot;Descripcion&quot;: &quot;   Conexión  [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string perfil_sistema_data {
            get {
                return ResourceManager.GetString("perfil_sistema_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `routeros_usage_stats` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`ServerId` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`json_data` LONGTEXT NOT NULL COLLATE &apos;utf8mb4_bin&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`PcHost` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`UsuarioCreo` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`FechaCreo` DATETIME NULL DEF [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string routeros_usage_stats {
            get {
                return ResourceManager.GetString("routeros_usage_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `server` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Descripcion` VARCHAR(30) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`IP` VARCHAR(30) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Puerto` SMALLINT(6) NULL DEFAULT NULL,
        ///	`Usuario` VARCHAR(2000) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Clave` VARCHAR(2000) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Predeterminado` CHAR(1) NULL DEFAULT &apos;N&apos; COLLATE &apos;utf8_general_ci&apos;,
        ///	`OsVersion` VARCHAR(50) NULL DEFAULT &apos;6.43&apos; COLLA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string server {
            get {
                return ResourceManager.GetString("server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `sys_config` (
        ///	`config` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`value` VARCHAR(500) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`value_bin` LONGBLOB NULL DEFAULT NULL,
        ///	`Activo` BIT(1) NULL DEFAULT b&apos;1&apos;
        ///)
        ///COMMENT=&apos;Configuraciones del programa&apos;
        ///COLLATE=&apos;utf8_general_ci&apos;
        ///ENGINE=InnoDB
        ///ROW_FORMAT=DYNAMIC
        ///;.
        /// </summary>
        internal static string sys_config {
            get {
                return ResourceManager.GetString("sys_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO sys_config(config, value, value_bin, Activo)VALUES(&apos;COM_NAME&apos;, &apos;Kaz Wifi - Company&apos;, NULL, 1);
        ///
        ///INSERT INTO sys_config(config, value, value_bin, Activo) VALUES(&apos;COM_DIR&apos;, &apos;&apos;, NULL, 1);
        ///
        ///INSERT INTO sys_config(config, value, value_bin, Activo)VALUES(&apos;COM_CONTACTS&apos;, &apos;info@kaz-wifi.com&apos;, NULL, 1);
        ///
        ///INSERT INTO sys_config (config, value, value_bin, Activo) VALUES(&apos;SYS_OPEN_DASH&apos;, &apos;0&apos;, NULL, 1);
        ///
        ///INSERT INTO sys_config(config, value, value_bin, Activo)VALUES(&apos;SYS_PRINT_USER_CRED_WIFI&apos;, &apos;1&apos;, NULL, 1); [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string sys_config_data {
            get {
                return ResourceManager.GetString("sys_config_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `usuario_hotspot` (
        ///	`Id` VARCHAR(25) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`IdServer` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`IdPerfil` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Usuario` VARCHAR(2000) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Clave` VARCHAR(2000) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Tiempo` INT(11) NULL DEFAULT NULL COMMENT &apos;Tiempo de Vigencia&apos;,
        ///	`TipoTiempo` CHAR(2) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Comentario` VA [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string usuario_hotspot {
            get {
                return ResourceManager.GetString("usuario_hotspot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE TABLE `usuario_sistema` (
        ///	`Id` VARCHAR(30) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Nombre` VARCHAR(50) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Apellido` VARCHAR(50) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Usuario` VARCHAR(30) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`Clave` VARCHAR(2000) NOT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`IdPerfil` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppId` VARCHAR(25) NULL DEFAULT NULL COLLATE &apos;utf8_general_ci&apos;,
        ///	`AppVersion` VARCHAR(25) NULL DEFAULT NULL C [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string usuario_sistema {
            get {
                return ResourceManager.GetString("usuario_sistema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REPLACE INTO `usuario_sistema` (`Id`, `Nombre`, `Apellido`, `Usuario`, `Clave`, `IdPerfil`, `AppId`, `AppVersion`, `PcHost`, `UsuarioCreo`, `FechaCreo`, `FechaElimino`, `UsuarioElimino`, `Token`, `Activo`) VALUES
        ///	(&apos;0&apos;, &apos;Administrador&apos;, &apos;de Sistema&apos;, &apos;ADMIN&apos;, &apos;VHy12nTdRpwD45wcP7F7oUJs9RBvs+srMw466Ui3wHQ=&apos;, &apos;20190626_224822_0747&apos;, NULL, NULL, NULL, NULL, NULL, NULL, NULL, &apos;1&apos;, b&apos;1&apos;);.
        /// </summary>
        internal static string usuario_sistema_data {
            get {
                return ResourceManager.GetString("usuario_sistema_data", resourceCulture);
            }
        }
    }
}
